image: Visual Studio 2017
configuration: Release
platform: Any CPU

environment:
  SOLUTION: ./src/WPF.Launcher.sln
  
#install:
#- cmd: git submodule update --init --recursive
build_script:
- cmd: MSBuild -restore /p:Configuration=Release /verbosity:minimal
artifacts:
- path: nugets/*.nupkg
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- echo %SOLUTION%
- cmd: nuget restore %SOLUTION% -verbosity detailed
build:
  verbosity: normal
  project: $(SOLUTION)
after_build:
- ps: "$files = get-childitem -recurse -Filter *.nuspec ($file in $files)\n{\n     $nuspec = $file.FullName\n     Write-Host(\"Packing \" + $nuspec + \" package\")\n     nuget pack $nuspec -version $env:APPVEYOR_BUILD_VERSION -OutputDirectory \"nugets\"\n}"
