image: Visual Studio 2017
configuration: Release
platform: Any CPU

environment:
  SOLUTION: ./src/WPF.Launcher.sln
  NUGET_REPO: nugets
  NUGET_VER: 1.0.4
  
#install:
#- cmd: git submodule update --init --recursive
build_script:
- cmd: MSBuild -restore /p:Configuration=Release /verbosity:minimal
artifacts:
- path: '**\*.nupkg'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- echo %NUGET_REPO%
- cmd: cmd /c mkdir %NUGET_REPO%
- echo %SOLUTION%
- cmd: nuget restore %SOLUTION% -verbosity detailed
build:
  verbosity: normal
  project: $(SOLUTION)
  publish_nuget: true
after_build:
- ps: "Set-Location -Path $env:APPVEYOR_BUILD_FOLDER\n $files = get-childitem -recurse -Filter \"*.nuspec\"\nforeach ($file in $files)\n{\n     $nuspec = $file.FullName\n     Write-Host(\"Packing \" + $nuspec + \" package\")\n     nuget pack $nuspec -version $env:APPVEYOR_BUILD_VERSION -OutputDirectory \"nugets\"\n}"
